import { WorkflowTemplate, AppNode, AppEdge } from '../types/workflow';
import { MarkerType } from '@xyflow/react';

export const PRESET_HR_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'employee-onboarding',
    title: 'Employee Onboarding Process',
    description: 'End-to-end standard onboarding flow covering identity verification, IT provisioning, welcome emails, and manager approval.',
    category: 'Onboarding',
    nodes: [
      {
        id: 'ob-start-1',
        type: 'start',
        position: { x: 50, y: 150 },
        data: {
          label: 'New Hire Accepted Offer',
          triggerType: 'form_submission',
          metadata: [
            { key: 'department', value: 'Engineering' },
            { key: 'work_mode', value: 'Hybrid' },
            { key: 'start_date', value: '2026-09-01' },
          ],
        },
      },
      {
        id: 'ob-task-1',
        type: 'task',
        position: { x: 380, y: 130 },
        data: {
          label: 'Collect & Verify Documents',
          description: 'Review signed employment contract, I-9 verification, and tax forms.',
          assignee: 'HR Operations Lead',
          dueDate: '2 Business Days',
          priority: 'high',
          customFields: [
            { key: 'passport_verified', value: 'true' },
            { key: 'direct_deposit_set', value: 'pending' },
          ],
        },
      },
      {
        id: 'ob-auto-1',
        type: 'automated',
        position: { x: 720, y: 130 },
        data: {
          label: 'Provision IT SSO & Laptop',
          actionId: 'provision_it_account',
          actionParams: {
            user_email: '{{candidate.email}}',
            role: 'Engineering_Dev',
            laptop_model: 'MacBook Pro M3 16"',
          },
        },
      },
      {
        id: 'ob-auto-2',
        type: 'automated',
        position: { x: 1060, y: 130 },
        data: {
          label: 'Send Welcome Orientation Email',
          actionId: 'send_email',
          actionParams: {
            to: '{{candidate.email}}',
            subject: 'Welcome to the Team! Day 1 Schedule',
            template: 'welcome_kit_v1',
          },
        },
      },
      {
        id: 'ob-appr-1',
        type: 'approval',
        position: { x: 1400, y: 130 },
        data: {
          label: 'Manager 30-Day Check-in Review',
          approverRole: 'Manager',
          threshold: 3,
          autoApproveUnit: 'days',
        },
      },
      {
        id: 'ob-end-1',
        type: 'end',
        position: { x: 1750, y: 150 },
        data: {
          label: 'Onboarding Completed',
          endMessage: 'Candidate successfully integrated into team with active credentials and payroll.',
          summaryFlag: true,
        },
      },
    ],
    edges: [
      {
        id: 'e-ob-1',
        source: 'ob-start-1',
        target: 'ob-task-1',
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
      },
      {
        id: 'e-ob-2',
        source: 'ob-task-1',
        target: 'ob-auto-1',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#3b82f6' },
      },
      {
        id: 'e-ob-3',
        source: 'ob-auto-1',
        target: 'ob-auto-2',
        animated: true,
        style: { stroke: '#a855f7', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#a855f7' },
      },
      {
        id: 'e-ob-4',
        source: 'ob-auto-2',
        target: 'ob-appr-1',
        animated: true,
        style: { stroke: '#a855f7', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#a855f7' },
      },
      {
        id: 'e-ob-5',
        source: 'ob-appr-1',
        sourceHandle: 'approved',
        target: 'ob-end-1',
        label: 'Approved',
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
        labelStyle: { fill: '#10b981', fontWeight: 600, fontSize: 11 },
      },
    ],
  },
  {
    id: 'leave-approval',
    title: 'Paid Time Off (PTO) & Leave Escalation',
    description: 'Multi-tiered leave request workflow with automatic manager approval SLA and Director escalation.',
    category: 'Leave & Absence',
    nodes: [
      {
        id: 'lv-start-1',
        type: 'start',
        position: { x: 50, y: 160 },
        data: {
          label: 'Leave Request Submitted',
          triggerType: 'form_submission',
          metadata: [
            { key: 'leave_type', value: 'Annual Vacation' },
            { key: 'duration_days', value: '5' },
          ],
        },
      },
      {
        id: 'lv-appr-1',
        type: 'approval',
        position: { x: 380, y: 140 },
        data: {
          label: 'Direct Manager PTO Approval',
          approverRole: 'Manager',
          threshold: 2,
          autoApproveUnit: 'days',
        },
      },
      {
        id: 'lv-auto-1',
        type: 'automated',
        position: { x: 740, y: 80 },
        data: {
          label: 'Update HRIS Calendar & Balance',
          actionId: 'update_hris',
          actionParams: {
            employee_id: '{{user.id}}',
            status: 'Approved_Leave',
          },
        },
      },
      {
        id: 'lv-auto-2',
        type: 'automated',
        position: { x: 1080, y: 80 },
        data: {
          label: 'Notify Team Channel on Slack',
          actionId: 'slack_notification',
          actionParams: {
            channel: '#team-engineering-ooo',
            message: '{{user.name}} will be on annual leave.',
            urgent: 'false',
          },
        },
      },
      {
        id: 'lv-end-1',
        type: 'end',
        position: { x: 1420, y: 100 },
        data: {
          label: 'Leave Finalized & Logged',
          endMessage: 'Calendar synced and balance deducted.',
          summaryFlag: false,
        },
      },
      {
        id: 'lv-end-2',
        type: 'end',
        position: { x: 740, y: 280 },
        data: {
          label: 'Leave Request Rejected',
          endMessage: 'Manager rejected leave request with feedback.',
          summaryFlag: false,
        },
      },
    ],
    edges: [
      {
        id: 'e-lv-1',
        source: 'lv-start-1',
        target: 'lv-appr-1',
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
      },
      {
        id: 'e-lv-2',
        source: 'lv-appr-1',
        sourceHandle: 'approved',
        target: 'lv-auto-1',
        label: 'Approved',
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
        labelStyle: { fill: '#10b981', fontWeight: 600, fontSize: 11 },
      },
      {
        id: 'e-lv-3',
        source: 'lv-appr-1',
        sourceHandle: 'rejected',
        target: 'lv-end-2',
        label: 'Rejected',
        animated: true,
        style: { stroke: '#ef4444', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#ef4444' },
        labelStyle: { fill: '#ef4444', fontWeight: 600, fontSize: 11 },
      },
      {
        id: 'e-lv-4',
        source: 'lv-auto-1',
        target: 'lv-auto-2',
        animated: true,
        style: { stroke: '#a855f7', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#a855f7' },
      },
      {
        id: 'e-lv-5',
        source: 'lv-auto-2',
        target: 'lv-end-1',
        animated: true,
        style: { stroke: '#a855f7', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#a855f7' },
      },
    ],
  },
  {
    id: 'doc-verification',
    title: 'Document Verification & Contract Signing',
    description: 'Background verification check, HRBP compliance review, and dynamic PDF contract generation.',
    category: 'Verification',
    nodes: [
      {
        id: 'dv-start-1',
        type: 'start',
        position: { x: 50, y: 150 },
        data: {
          label: 'Background Check Requested',
          triggerType: 'system_event',
          metadata: [
            { key: 'screening_vendor', value: 'Checkr' },
            { key: 'package', value: 'Comprehensive' },
          ],
        },
      },
      {
        id: 'dv-task-1',
        type: 'task',
        position: { x: 380, y: 130 },
        data: {
          label: 'Review Screening Results',
          description: 'Ensure clean background check report and education credentials.',
          assignee: 'HR Compliance Officer',
          dueDate: '24 Hours',
          priority: 'urgent',
          customFields: [{ key: 'criminal_check', value: 'cleared' }],
        },
      },
      {
        id: 'dv-appr-1',
        type: 'approval',
        position: { x: 720, y: 130 },
        data: {
          label: 'HRBP Risk Clearance',
          approverRole: 'HRBP',
          threshold: 1,
          autoApproveUnit: 'days',
        },
      },
      {
        id: 'dv-auto-1',
        type: 'automated',
        position: { x: 1060, y: 130 },
        data: {
          label: 'Generate Official Offer Letter PDF',
          actionId: 'generate_doc',
          actionParams: {
            template: 'FullTime_Contract',
            recipient: '{{candidate.name}}',
            format: 'PDF/A',
          },
        },
      },
      {
        id: 'dv-end-1',
        type: 'end',
        position: { x: 1400, y: 150 },
        data: {
          label: 'Verification Passed & Letter Sent',
          endMessage: 'Candidate cleared background check and received legally binding contract.',
          summaryFlag: true,
        },
      },
    ],
    edges: [
      {
        id: 'e-dv-1',
        source: 'dv-start-1',
        target: 'dv-task-1',
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
      },
      {
        id: 'e-dv-2',
        source: 'dv-task-1',
        target: 'dv-appr-1',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#3b82f6' },
      },
      {
        id: 'e-dv-3',
        source: 'dv-appr-1',
        sourceHandle: 'approved',
        target: 'dv-auto-1',
        label: 'Approved',
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
        labelStyle: { fill: '#10b981', fontWeight: 600, fontSize: 11 },
      },
      {
        id: 'e-dv-4',
        source: 'dv-auto-1',
        target: 'dv-end-1',
        animated: true,
        style: { stroke: '#a855f7', strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: '#a855f7' },
      },
    ],
  },
];
